### ISSUE TITLE
Not working correctly

### ISSUE THREAD

**Issue by KasonBraley** [martinlindhe/inputbox#3]
The first example provided does not work properly. Regardless if "OK" or "Cancel" is clicked, the Boolean seems to always be false and thus triggers the else block.

**Comment by martinlindhe** [comment]
I'm sorry to hear.
What operating system are you using?

**Comment by martinlindhe** [comment]
I am unable to reproduce your issue. So I will assume user error and close this one. If you have additional info, please write here or open a new issue.
